; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64--linux-gnu -mattr=+sve < %s | FileCheck %s

define void @masked_gather_prefetch_nxv2i8(<vscale x 2 x i8*> %ptrs, <vscale x 2 x i1> %mask) {
; CHECK-LABEL: masked_gather_prefetch_nxv2i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    prfb pldl1keep, p0, [z0.d]
; CHECK-NEXT:    ret
  call void @llvm.masked.gather.prefetch.nxv2p0(<vscale x 2 x ptr> %ptrs, i32 1, i32 0, i32 3, <vscale x 2 x i1> %mask)
  ret void
}

define void @masked_gather_prefetch_nxv2i16(<vscale x 2 x i16*> %ptrs, <vscale x 2 x i1> %mask) {
; CHECK-LABEL: masked_gather_prefetch_nxv2i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    prfh pldl1keep, p0, [z0.d]
; CHECK-NEXT:    ret
  call void @llvm.masked.gather.prefetch.nxv2p0(<vscale x 2 x ptr> %ptrs, i32 2, i32 0, i32 3, <vscale x 2 x i1> %mask)
  ret void
}

define void @masked_gather_prefetch_nxv2i32(<vscale x 2 x i32*> %ptrs, <vscale x 2 x i1> %mask) {
; CHECK-LABEL: masked_gather_prefetch_nxv2i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    prfw pldl1keep, p0, [z0.d]
; CHECK-NEXT:    ret
  call void @llvm.masked.gather.prefetch.nxv2p0(<vscale x 2 x ptr> %ptrs, i32 4, i32 0, i32 3, <vscale x 2 x i1> %mask)
  ret void
}

define void @masked_gather_prefetch_nxv2i64(<vscale x 2 x i64*> %ptrs, <vscale x 2 x i1> %mask) {
; CHECK-LABEL: masked_gather_prefetch_nxv2i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    prfd pldl1keep, p0, [z0.d]
; CHECK-NEXT:    ret
  call void @llvm.masked.gather.prefetch.nxv2p0(<vscale x 2 x ptr> %ptrs, i32 8, i32 0, i32 3, <vscale x 2 x i1> %mask)
  ret void
}

define void @masked_gather_prefetch_nxv4i8(<vscale x 4 x i8*> %ptrs, <vscale x 4 x i1> %mask) {
; CHECK-LABEL: masked_gather_prefetch_nxv4i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    punpklo p1.h, p0.b
; CHECK-NEXT:    punpkhi p0.h, p0.b
; CHECK-NEXT:    prfb pldl1keep, p1, [z0.d]
; CHECK-NEXT:    prfb pldl1keep, p0, [z1.d]
; CHECK-NEXT:    ret
  call void @llvm.masked.gather.prefetch.nxv4p0(<vscale x 4 x ptr> %ptrs, i32 1, i32 0, i32 3, <vscale x 4 x i1> %mask)
  ret void
}

define void @masked_gather_prefetch_nxv4i16(<vscale x 4 x i16*> %ptrs, <vscale x 4 x i1> %mask) {
; CHECK-LABEL: masked_gather_prefetch_nxv4i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    punpklo p1.h, p0.b
; CHECK-NEXT:    punpkhi p0.h, p0.b
; CHECK-NEXT:    prfh pldl1keep, p1, [z0.d]
; CHECK-NEXT:    prfh pldl1keep, p0, [z1.d]
; CHECK-NEXT:    ret
  call void @llvm.masked.gather.prefetch.nxv4p0(<vscale x 4 x ptr> %ptrs, i32 2, i32 0, i32 3, <vscale x 4 x i1> %mask)
  ret void
}

define void @masked_gather_prefetch_nxv4i32(<vscale x 4 x i32*> %ptrs, <vscale x 4 x i1> %mask) {
; CHECK-LABEL: masked_gather_prefetch_nxv4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    punpklo p1.h, p0.b
; CHECK-NEXT:    punpkhi p0.h, p0.b
; CHECK-NEXT:    prfw pldl1keep, p1, [z0.d]
; CHECK-NEXT:    prfw pldl1keep, p0, [z1.d]
; CHECK-NEXT:    ret
  call void @llvm.masked.gather.prefetch.nxv4p0(<vscale x 4 x ptr> %ptrs, i32 4, i32 0, i32 3, <vscale x 4 x i1> %mask)
  ret void
}

define void @masked_gather_prefetch_nxv4i64(<vscale x 4 x i64*> %ptrs, <vscale x 4 x i1> %mask) {
; CHECK-LABEL: masked_gather_prefetch_nxv4i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    punpklo p1.h, p0.b
; CHECK-NEXT:    punpkhi p0.h, p0.b
; CHECK-NEXT:    prfd pldl1keep, p1, [z0.d]
; CHECK-NEXT:    prfd pldl1keep, p0, [z1.d]
; CHECK-NEXT:    ret
  call void @llvm.masked.gather.prefetch.nxv4p0(<vscale x 4 x ptr> %ptrs, i32 8, i32 0, i32 3, <vscale x 4 x i1> %mask)
  ret void
}

declare void @llvm.masked.gather.prefetch.nxv2p0(<vscale x 2 x ptr>, i32, i32, i32, <vscale x 2 x i1>)
declare void @llvm.masked.gather.prefetch.nxv4p0(<vscale x 4 x ptr>, i32, i32, i32, <vscale x 4 x i1>)
attributes #0 = { "target-features"="+sve,+bf16" }
